language: php

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.2

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS 1989_test;'

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
