language: php

services:
  - mysql

php:
  - 7.2

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS 1989_test;'

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
